let NFTitem = [
    {
    link: "product-detail",
    src: "NFT1.png",
    name: "Doodle",
    avt: "avt.png",
    author: "0x60...9B38",
    price: "8.0",
  },
  {
    link: "product-detail",
    src: "NFT1.png",
    name: "Doodle",
    avt: "avt.png",
    author: "0x60...9B38",
    price: "8.0",
  },
  {
    link: "product-detail",
    src: "NFT1.png",
    name: "Doodle",
    avt: "avt.png",
    author: "0x60...9B38",
    price: "8.0",
  },
  {
    link: "product-detail",
    src: "NFT1.png",
    name: "Doodle",
    avt: "avt.png",
    author: "0x60...9B38",
    price: "8.0",
  },
  {
    link: "product-detail",
    src: "NFT1.png",
    name: "Doodle",
    avt: "avt.png",
    author: "0x60...9B38",
    price: "8.0",
  },
  {
    link: "product-detail",
    src: "NFT1.png",
    name: "Doodle",
    avt: "avt.png",
    author: "0x60...9B38",
    price: "8.0",
  },
]